# Generated by Django 2.2.5 on 2020-03-05 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiptapp', '0002_fooddetail_after_eat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=50)),
                ('progress_no', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
