# Generated by Django 2.2.5 on 2020-03-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiptapp', '0003_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='id',
        ),
        migrations.AlterField(
            model_name='progress',
            name='task_id',
            field=models.CharField(max_length=60, primary_key=True, serialize=False),
        ),
    ]
