# Generated by Django 2.2.5 on 2019-12-09 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('receiptapp', '0003_auto_20191117_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='receipt_id',
        ),
        migrations.RemoveField(
            model_name='image',
            name='receipt_id',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='user_id',
        ),
        migrations.AddField(
            model_name='food',
            name='food_name',
            field=models.CharField(default='default_food', max_length=50),
        ),
        migrations.AddField(
            model_name='image',
            name='receipt',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='receiptapp.Receipt'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='food_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='receiptapp.Food'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='food',
            name='food_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='food',
            name='protein',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='salt',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='zinc',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='receipt_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
