# Generated by Django 2.2.5 on 2019-12-09 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receiptapp', '0004_auto_20191209_1959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='food_id',
            new_name='food',
        ),
        migrations.RemoveField(
            model_name='image',
            name='receipt',
        ),
        migrations.AddField(
            model_name='receipt',
            name='image',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='receiptapp.Image'),
        ),
    ]
