# Generated by Django 2.2.5 on 2019-12-11 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiptapp', '0005_auto_20191209_2019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='zinc',
            new_name='carb',
        ),
        migrations.AddField(
            model_name='food',
            name='energy',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='fat',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
