# Generated by Django 2.2.5 on 2019-12-11 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiptapp', '0006_auto_20191211_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='receiptapp/'),
        ),
    ]
