# Generated by Django 2.2.5 on 2019-12-11 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiptapp', '0007_auto_20191211_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='food_id',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image_id',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='receipt_id',
        ),
        migrations.AddField(
            model_name='food',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receipt',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
