# Generated by Django 2.2.5 on 2019-12-13 15:50

from django.db import migrations, models
import receiptapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('receiptapp', '0008_auto_20191211_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=receiptapp.models.get_image_path),
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='food',
        ),
        migrations.AddField(
            model_name='receipt',
            name='food',
            field=models.ManyToManyField(default=0, to='receiptapp.Food'),
        ),
    ]
