# Generated by Django 2.2.5 on 2019-12-14 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiptapp', '0010_auto_20191214_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='foods',
            field=models.ManyToManyField(blank=True, to='receiptapp.Food'),
        ),
    ]
