# Generated by Django 2.2.5 on 2019-12-15 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiptapp', '0011_auto_20191215_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='carb',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='energy',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='fat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='protein',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='salt',
            field=models.FloatField(),
        ),
    ]
