# Generated by Django 2.2.5 on 2019-12-17 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receiptapp', '0014_auto_20191215_2329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField()),
                ('receipt', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='receiptapp.Receipt')),
            ],
        ),
    ]
