# Generated by Django 2.2.5 on 2019-12-17 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receiptapp', '0015_food_detail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Food_detail',
            new_name='Fooddetail',
        ),
    ]
