# Generated by Django 2.2.5 on 2019-12-29 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receiptapp', '0016_auto_20191217_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='foods',
        ),
        migrations.AddField(
            model_name='fooddetail',
            name='food',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='receiptapp.Food'),
        ),
    ]
